version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=<key>

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend